language: C
install:
  - sudo apt-get -y install libmyodbc unixodbc-dev
  - sudo odbcinst -i -d -f /usr/share/libmyodbc/odbcinst.ini
env:
  - CFLAGS=-I/usr/include/unixodbc
script:
  - make
  - make test
  - ./test
