language: C
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
os: linux
install:
  - sudo apt-get -y install mysql-server libssl-dev unixodbc-dev
  - sudo chmod 644 /etc/mysql/debian.cnf
  - sudo systemctl restart mysql
  - wget https://downloads.mariadb.org/interstitial/connector-c-3.1.5/mariadb-connector-c-3.1.5-src.tar.gz
  - wget https://downloads.mariadb.org/interstitial/connector-odbc-3.1.5/mariadb-connector-odbc-3.1.5-ga-src.tar.gz
  - mkdir -p mariadb-odbc/libmariadb mariadb-odbc/build
  - tar -xvzf mariadb-connector-odbc-3.1.5-ga-src.tar.gz --strip-components=1 -C mariadb-odbc
  - tar -xvzf mariadb-connector-c-3.1.5-src.tar.gz --strip-components=1 -C mariadb-odbc/libmariadb
  - sh -c "cd mariadb-odbc/build; cmake -DODBC_LIB_DIR=/usr/lib/$(dpkg-architecture -q DEB_HOST_GNU_TYPE) ..; make"
script:
  - make
  - make -C tests test
  - ./tests/test ./mariadb-odbc/build/libmaodbc.so $(awk '/user/{print$3;exit}' /etc/mysql/debian.cnf) $(awk '/password/{print$3;exit}' /etc/mysql/debian.cnf)
  - make -C tests test-so
  - ./tests/test-so ./mariadb-odbc/build/libmaodbc.so $(awk '/user/{print$3;exit}' /etc/mysql/debian.cnf) $(awk '/password/{print$3;exit}' /etc/mysql/debian.cnf)
